name: Publish
permissions: write-all

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Replace Vversion
        id: replace_version
        uses: mad9000/actions-find-and-replace-string@5
        with:
          source: ${{ github.ref_name }}
          find: 'v'
          replace: ''
      - name: Install and build and package
        env:
          version_number: ${{ steps.replace_version.outputs.value }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm install
          npm install typescript -g
          tsc --version
          npm run-script build
          cd build
          sh ../npm_login.sh
          npm publish
      

